import React, { useState, useEffect } from "react";
import "./QuizSetup.css";

export default function QuizSetup() {
  const [quiz, setQuiz] = useState({
    className: "",
    subject: "",
    difficulty: "",
    numTopics: 1,
    topics: [],
  });

  const [availableTopics, setAvailableTopics] = useState([]); // Topics from backend

  // Fetch topic names from backend on mount
  useEffect(() => {
    const fetchTopics = async () => {
      try {
        const res = await fetch(
          "https://your-backend-url.com/api/topics" // Replace with your endpoint
        );
        if (!res.ok) throw new Error("Failed to fetch topics");
        const data = await res.json();
        setAvailableTopics(data); // Expecting an array of topic names
      } catch (err) {
        console.error(err);
        alert("Error fetching topics from backend");
      }
    };
    fetchTopics();
  }, []);

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setQuiz((prev) => ({ ...prev, [name]: value }));
  };

  const generateTopics = () => {
    const topicsArray = [];
    const num = parseInt(quiz.numTopics) || 1;
    for (let i = 0; i < num; i++) {
      topicsArray.push({
        name: "",
        ai: 0,
        db: 0,
        total: 0,
        warning: false,
      });
    }
    setQuiz((prev) => ({ ...prev, topics: topicsArray }));
  };

  const handleTopicChange = (index, field, value) => {
    setQuiz((prev) => {
      const topics = [...prev.topics];
      topics[index][field] = parseInt(value) || 0;

      // Update total and warning
      const total = topics[index].ai + topics[index].db;
      topics[index].total = total > 35 ? 35 : total;
      topics[index].warning = total > 35;

      return { ...prev, topics };
    });
  };

  const handleTopicNameChange = (index, value) => {
    setQuiz((prev) => {
      const topics = [...prev.topics];
      topics[index].name = value;
      return { ...prev, topics };
    });
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    for (let topic of quiz.topics) {
      if (topic.total > 35) {
        alert("Total questions for any topic cannot exceed 35.");
        return;
      }
    }
    console.log("Quiz Setup:", quiz);
    alert("Check console for quiz setup object.");
  };

  return (
    <div className="quiz-setup-container">
      <h2>Quiz Setup</h2>
      <form onSubmit={handleSubmit}>
        <label>Class:</label>
        <select
          name="className"
          value={quiz.className}
          onChange={handleInputChange}
          required
        >
          <option value="">Select Class</option>
          <option value="kindergarten">Kindergarten</option>
          <option value="selective">Selective</option>
          <option value="year1">Year 1</option>
          <option value="year2">Year 2</option>
          <option value="year3">Year 3</option>
          <option value="year4">Year 4</option>
          <option value="year5">Year 5</option>
          <option value="year6">Year 6</option>
        </select>

        <label>Subject:</label>
        <select
          name="subject"
          value={quiz.subject}
          onChange={handleInputChange}
          required
        >
          <option value="">Select Subject</option>
          <option value="thinking_skills">Thinking Skills</option>
          <option value="mathematical_reasoning">Mathematical Reasoning</option>
          <option value="reading">Reading</option>
          <option value="writing">Writing</option>
        </select>

        <label>Difficulty Level:</label>
        <select
          name="difficulty"
          value={quiz.difficulty}
          onChange={handleInputChange}
          required
        >
          <option value="">Select Difficulty</option>
          <option value="easy">Easy</option>
          <option value="medium">Medium</option>
          <option value="hard">Hard</option>
        </select>

        <label>Number of Topics:</label>
        <input
          type="number"
          name="numTopics"
          min="1"
          value={quiz.numTopics}
          onChange={handleInputChange}
        />

        <button type="button" onClick={generateTopics}>
          Generate Topics
        </button>

        <div className="topics-container">
          {quiz.topics.map((topic, index) => (
            <div className="topic" key={index}>
              <h4>Topic {index + 1}</h4>

              <label>Topic Name:</label>
              <select
                value={topic.name}
                onChange={(e) => handleTopicNameChange(index, e.target.value)}
                required
              >
                <option value="">Select Topic</option>
                {availableTopics.map((t, i) => (
                  <option key={i} value={t}>
                    {t}
                  </option>
                ))}
              </select>

              <label>Questions Generated by AI:</label>
              <input
                type="number"
                min="0"
                value={topic.ai}
                onChange={(e) => handleTopicChange(index, "ai", e.target.value)}
                required
              />

              <label>Questions from Database:</label>
              <input
                type="number"
                min="0"
                value={topic.db}
                onChange={(e) => handleTopicChange(index, "db", e.target.value)}
                required
              />

              <label>Total Questions:</label>
              <input type="number" value={topic.total} readOnly />
              {topic.warning && <div className="warning">Total cannot exceed 35!</div>}
            </div>
          ))}
        </div>

        <button type="submit">Submit Quiz Setup</button>

        <p className="note">
          Note: The number of questions generated—either by AI or from your database—will be configured in the backend based on your preferences. Total questions per topic cannot exceed 35.
        </p>
      </form>
    </div>
  );
}
