import React, { useState } from "react";
import "./QuizSetup.css";

export default function QuizSetup() {
  const [quiz, setQuiz] = useState({
    className: "",
    subject: "",
    difficulty: "",
    numTopics: 1,
    topics: [],
  });

  const [totalQuestions, setTotalQuestions] = useState(0);

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setQuiz((prev) => ({ ...prev, [name]: value }));
  };

  const generateTopics = () => {
    const num = parseInt(quiz.numTopics) || 1;
    const topicsArray = [];

    for (let i = 0; i < num; i++) {
      topicsArray.push({
        name: "",
        ai: 0,
        db: 0,
        warning: false,
      });
    }

    setQuiz((prev) => ({ ...prev, topics: topicsArray }));
    setTotalQuestions(0);
  };

  const handleTopicChange = (index, field, value) => {
    setQuiz((prev) => {
      const topics = [...prev.topics];
      topics[index][field] = parseInt(value) || 0;

      // Recalculate total for ALL topics
      const newTotal = topics.reduce(
        (acc, t) => acc + (parseInt(t.ai) || 0) + (parseInt(t.db) || 0),
        0
      );

      setTotalQuestions(newTotal);

      return { ...prev, topics };
    });
  };

  const handleTopicNameChange = (index, value) => {
    setQuiz((prev) => {
      const topics = [...prev.topics];
      topics[index].name = value;
      return { ...prev, topics };
    });
  };

  const handleSubmit = async (e) => {
  e.preventDefault();

  if (totalQuestions > 40) {
    alert("Total questions across all topics cannot exceed 40.");
    return;
  }

  // Prepare payload for backend
  const payload = {
    class_name: quiz.className,
    subject: quiz.subject,
    difficulty: quiz.difficulty,
    num_topics: quiz.topics.length,
    topics: quiz.topics.map((t) => ({
      name: t.name,
      ai: t.ai,
      db: t.db,
      total: t.total,
    })),
  };

  try {
    const res = await fetch("https://your-backend-url.com/api/quizzes", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(payload),
    });

    if (!res.ok) throw new Error("Failed to save quiz setup");

    const data = await res.json();
    console.log("Quiz saved:", data);
    alert("Quiz setup saved successfully!");

  } catch (error) {
    console.error(error);
    alert("Error saving quiz setup. Please try again.");
  }
};

  return (
    <div className="quiz-setup-container">
      <form onSubmit={handleSubmit}>

        <label>Class:</label>
        <select
          name="className"
          value={quiz.className}
          onChange={handleInputChange}
          required
        >
          <option value="">Select Class</option>
          <option value="kindergarten">Kindergarten</option>
          <option value="selective">Selective</option>
          <option value="year1">Year 1</option>
          <option value="year2">Year 2</option>
          <option value="year3">Year 3</option>
          <option value="year4">Year 4</option>
          <option value="year5">Year 5</option>
          <option value="year6">Year 6</option>
        </select>

        <label>Subject:</label>
        <select
          name="subject"
          value={quiz.subject}
          onChange={handleInputChange}
          required
        >
          <option value="">Select Subject</option>
          <option value="thinking_skills">Thinking Skills</option>
          <option value="mathematical_reasoning">Mathematical Reasoning</option>
          <option value="reading">Reading</option>
          <option value="writing">Writing</option>
        </select>

        <label>Difficulty Level:</label>
        <select
          name="difficulty"
          value={quiz.difficulty}
          onChange={handleInputChange}
          required
        >
          <option value="">Select Difficulty</option>
          <option value="easy">Easy</option>
          <option value="medium">Medium</option>
          <option value="hard">Hard</option>
        </select>

        <label>Number of Topics:</label>
        <input
          type="number"
          name="numTopics"
          min="1"
          value={quiz.numTopics}
          onChange={handleInputChange}
        />

        <button type="button" onClick={generateTopics}>
          Generate Topics
        </button>

        <div className="topics-container">
          {quiz.topics.map((topic, index) => (
            <div className="topic" key={index}>
              <h4>Topic {index + 1}</h4>

              <label>Topic Name:</label>
              <input
                type="text"
                value={topic.name}
                onChange={(e) => handleTopicNameChange(index, e.target.value)}
                required
              />

              <label>Questions Generated by AI:</label>
              <input
                type="number"
                min="0"
                value={topic.ai}
                onChange={(e) => handleTopicChange(index, "ai", e.target.value)}
                required
              />

              <label>Questions from Database:</label>
              <input
                type="number"
                min="0"
                value={topic.db}
                onChange={(e) => handleTopicChange(index, "db", e.target.value)}
                required
              />
            </div>
          ))}
        </div>

        {/* Global Total Questions Below All Topics */}
        <div className="total-section">
          <h3>Total Questions: {totalQuestions}</h3>
          {totalQuestions > 40 && (
            <div className="warning">Total cannot exceed 40!</div>
          )}
        </div>

        <button type="submit" disabled={totalQuestions > 40}>
          Submit
        </button>

      </form>
    </div>
  );
}
