import React, { useState } from "react";
import "./QuizSetup.css";

export default function QuizSetup() {
  const [quiz, setQuiz] = useState({
    className: "",
    subject: "",
    difficulty: "",
    numTopics: 1,
    topics: [],
  });

  const [totalCount, setTotalCount] = useState(0);
  const [totalWarning, setTotalWarning] = useState(false);

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setQuiz((prev) => ({ ...prev, [name]: value }));
  };

  const generateTopics = () => {
    const num = parseInt(quiz.numTopics) || 1;
    const topicsArray = [];

    for (let i = 0; i < num; i++) {
      topicsArray.push({
        name: "",
        ai: 0,
        db: 0,
      });
    }

    setQuiz((prev) => ({ ...prev, topics: topicsArray }));
    setTotalCount(0);
    setTotalWarning(false);
  };

  const handleTopicChange = (index, field, value) => {
    const newValue = parseInt(value) || 0;

    setQuiz((prev) => {
      const topics = [...prev.topics];
      topics[index][field] = newValue;

      // Recalculate cumulative total
      const newTotal = topics.reduce(
        (sum, t) => sum + (parseInt(t.ai) || 0) + (parseInt(t.db) || 0),
        0
      );

      setTotalCount(newTotal);
      setTotalWarning(newTotal > 40);

      return { ...prev, topics };
    });
  };

  const handleTopicNameChange = (index, value) => {
    setQuiz((prev) => {
      const topics = [...prev.topics];
      topics[index].name = value;
      return { ...prev, topics };
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (totalCount > 40) {
      alert("The total number of questions across all topics cannot exceed 40.");
      return;
    }

    try {
      const res = await fetch("https://your-backend-url.com/api/save-quiz", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(quiz),
      });

      if (!res.ok) throw new Error("Failed to save quiz.");

      alert("Quiz saved successfully!");
    } catch (error) {
      console.error(error);
      alert("Failed to submit quiz.");
    }
  };

  return (
    <div className="quiz-setup-container">
      <form onSubmit={handleSubmit}>

        <label>Class:</label>
        <select
          name="className"
          value={quiz.className}
          onChange={handleInputChange}
          required
        >
          <option value="">Select Class</option>
          <option value="kindergarten">Kindergarten</option>
          <option value="selective">Selective</option>
          <option value="year1">Year 1</option>
          <option value="year2">Year 2</option>
          <option value="year3">Year 3</option>
          <option value="year4">Year 4</option>
          <option value="year5">Year 5</option>
          <option value="year6">Year 6</option>
        </select>

        <label>Subject:</label>
        <select
          name="subject"
          value={quiz.subject}
          onChange={handleInputChange}
          required
        >
          <option value="">Select Subject</option>
          <option value="thinking_skills">Thinking Skills</option>
          <option value="mathematical_reasoning">Mathematical Reasoning</option>
          <option value="reading">Reading</option>
          <option value="writing">Writing</option>
        </select>

        <label>Difficulty:</label>
        <select
          name="difficulty"
          value={quiz.difficulty}
          onChange={handleInputChange}
          required
        >
          <option value="">Select Difficulty</option>
          <option value="easy">Easy</option>
          <option value="medium">Medium</option>
          <option value="hard">Hard</option>
        </select>

        <label>Number of Topics:</label>
        <input
          type="number"
          name="numTopics"
          min="1"
          value={quiz.numTopics}
          onChange={handleInputChange}
        />

        <button type="button" onClick={generateTopics}>
          Generate Topics
        </button>

        <div className="topics-container">
          {quiz.topics.map((topic, index) => (
            <div className="topic" key={index}>
              <h4>Topic {index + 1}</h4>

              <label>Topic Name:</label>
              <input
                type="text"
                value={topic.name}
                onChange={(e) =>
                  handleTopicNameChange(index, e.target.value)
                }
                required
              />

              <label>Questions Generated by AI:</label>
              <input
                type="number"
                min="0"
                value={topic.ai}
                onChange={(e) =>
                  handleTopicChange(index, "ai", e.target.value)
                }
                required
              />

              <label>Questions from Database:</label>
              <input
                type="number"
                min="0"
                value={topic.db}
                onChange={(e) =>
                  handleTopicChange(index, "db", e.target.value)
                }
                required
              />
            </div>
          ))}
        </div>

        {/* SINGLE cumulative total */}
        <h3>Total Questions Across All Topics: {totalCount}</h3>
        {totalWarning && (
          <p className="warning">Total cannot exceed 40 questions!</p>
        )}

        <button type="submit">Submit Quiz Setup</button>

        <p className="note">
          Total questions (AI + DB combined across all topics) cannot exceed 40.
        </p>
      </form>
    </div>
  );
}
